language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install --no-interaction

script:
  - vendor/bin/phpunit